- hosts: all
  remote_user: '{{ deploy_user }}'
  tasks:
    - name: Clean older images
      community.docker.docker_prune:
        containers: true
        images: yes
        images_filters:
          dangling: false
          until: 24h
        volumes: true
        builder_cache: true