all:
  vars:
    name: taxomap
    domain: taxomap.geomatico.es
    compose_path: /srv/services/taxomap
    deploy_user: geomatico
    letsencrypt_mail: francisco.perez@geomatico.es
    geoserver_url: https://taxomap.geomatico.es/geoserver
    postgres_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      63323638313731636638333532303430353066653730646631363762366236313965316235396565
      6330353234393861383961353538613238386264383538330a653430326136633532353934343861
      31616630353966666238343739323434643164653037393634613437373365353238363764356438
      3933356232373766620a626131383237643738613061336432356633383761356561383736383064
      66323130633465326164623232646164663065396365316139343735383462336162
    postgres_taxomap_user: taxomap
    postgres_taxomap_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66373462353832373632653234663139646565313933646537353536613239343566346332633238
      3137633339316632353331323931663962376632653639640a316564323330333539633532393966
      64613234666630393662666663373262646566306337303639373034323832313331626466303537
      3863633534316131350a303732623033663865366434653463333631373562336163653663353430
      63623139623837653130393963333236346362313236316434353637366363313434
    geoserver_admin_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33343134386635633333333463633062323839643031646663616439373864343232353834623634
      3465333966366130636332336662383966636332663932310a336339383234646665623366383836
      63333036363265613930356238643639343130386265306335343133366132363164393966666366
      6538343933333961640a353136343732346266346165303431353330343362646533306130356536
      37626364643761336465336536656663643637653730623632646136326434393438

  hosts:
    37.187.151.226:
