name: Deploy to stage
on:
  workflow_dispatch:
# TODO TAX-67 enable when prod/staging are different envs
#  push:
#    branches:
#      - main
jobs:
  upload:
    name: Build and Upload Images to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: create ansible vault file
        run: |
          echo ${{ secrets.ANSIBLE_VAULT }} > ~/.vaultfile

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: run deploy playbook
        working-directory: ./devops
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_VAULT_PASSWORD_FILE: ~/.vaultfile
        run: |
          ansible-playbook -i inventories/prod-geomatico.yml upload_images.yml

  deploy:
    name: Deploy Taxomap Services
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: create ansible vault file
        run: |
          echo ${{ secrets.ANSIBLE_VAULT }} > ~/.vaultfile

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: run deploy playbook
        working-directory: ./devops
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_VAULT_PASSWORD_FILE: ~/.vaultfile
        run: |
          ansible-playbook -i inventories/prod-geomatico.yml deploy.yml

  prune_images:
    name: Prune Images
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: create ansible vault file
        run: |
          echo ${{ secrets.ANSIBLE_VAULT }} > ~/.vaultfile

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: run deploy playbook
        working-directory: ./devops
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_VAULT_PASSWORD_FILE: ~/.vaultfile
        run: |
          ansible-playbook -i inventories/prod-geomatico.yml prune_images.yml