name: Push prod images
on:
  workflow_dispatch:

concurrency:
  group: push_prod_images
  cancel-in-progress: false

defaults:
  run:
    working-directory: ./devops

jobs:
  backend-tests:
    uses: ./.github/workflows/test-backend.yml
    secrets:
      DJANGO_PIPELINE: ${{ secrets.DJANGO_PIPELINE }}
  frontend-tests:
    uses: ./.github/workflows/test-frontend.yml

  upload:
    name: Build and upload images
    needs: [backend-tests, frontend-tests]
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: create ansible vault file
        run: echo ${{ secrets.ANSIBLE_STAGING_VAULT }} > ~/.vaultfile

      - name: run upload-images playbook
        run: ansible-playbook -i inventories/prod.yml upload-production-images.yml
